### PR TITLE
Debugging at hardware raspi

### PR DESCRIPTION
**Pull request by Acer54**
Testing and debugging at hardware-level is more or less finished. 
Some minor issues might be still there, but I hope that they will come up during further development.

I've fixed also the other themes (resources-file was still created with pyrcc4 instead of 5)

### CODE REVIEW

**Comment by HiranChaudhuri** [comment]
I resolved the fact that this branch was four commits behind master, however during testing I found two issues:

* I ran into this error:
```
2019-12-14 22:41:20,955 - ERROR - webradio - Dummy-1 - Uncaught exception
Traceback (most recent call last):
  File "/opt/webradio-py3/lib/mpd_daemon.py", line 255, in run
    self.function(*self.args,**self.kwargs)
  File "/opt/webradio-py3/lib/mpd_daemon.py", line 72, in __run_notifier
    self.__observe_mpd()
  File "/opt/webradio-py3/lib/mpd_daemon.py", line 224, in __observe_mpd
    self.sig_mpd_media_local_changed.emit(current_url,current_song,current_artist,current_album)
TypeError: MPD_Eventlistener.sig_mpd_media_local_changed[str, str, str, str].emit(): argument 4 has unexpected type 'list'
```

* The sleeptimer displays a bit unfortunate on my 800x480 screen
2019-12-14-220311_800x480_scrot

**Comment by HiranChaudhuri** [comment]
While testing some more (I am actually just restarting Raspberry several times) I get this error:
```
2019-12-14 23:05:39,760 - ERROR - webradio - MainThread - Uncaught exception
Traceback (most recent call last):
  File "./webradio.py", line 3942, in <module>
    mainwindow.startup_actions()
  File "./webradio.py", line 1097, in startup_actions
    __readSettings(self)
  File "./webradio.py", line 1065, in __readSettings
    self.switchModeTo(self.mode, self.mode)
  File "./webradio.py", line 1613, in switchModeTo
    self.player = MPC_Player()
  File "/opt/webradio-py3/lib/players.py", line 64, in __init__
    self.client.load("favorites")
  File "/usr/lib/python3/dist-packages/mpd/base.py", line 381, in mpd_command
    return wrapper(self, name, args, callback)
  File "/usr/lib/python3/dist-packages/mpd/base.py", line 473, in _execute
    return retval()
  File "/usr/lib/python3/dist-packages/mpd/base.py", line 368, in command_callback
    res = function(self, self._read_lines())
  File "/usr/lib/python3/dist-packages/mpd/base.py", line 311, in _parse_nothing
    for line in lines:
  File "/usr/lib/python3/dist-packages/mpd/base.py", line 538, in _read_lines
    line = self._read_line()
  File "/usr/lib/python3/dist-packages/mpd/base.py", line 527, in _read_line
    raise CommandError(error)
mpd.base.CommandError: [50@0] {} No such playlist

```

As the configuration of mpd seems to have changed (for whatever reason) I'd say this is not a fault worth to terminate webradio. Instead the user should be able to create his playlist.

**Comment by HiranChaudhuri** [comment]
Now that the playlist was not found Webradio comes up with a strange screen. To me it looks like the MP3 player but the title says Web Radio Tuner. This automatically reverts to normal operation as soon some mode is changed.

2019-12-14-233658_800x480_scrot

**Comment by HiranChaudhuri** [comment]
So it seems my playlist for MPD and Webradio are out of sync. While I keep getting warnings that the favorites playlist cannot get loaded, the UI presents me with my former radio stations. Whichever I choose - it cannot be played.

**Comment by HiranChaudhuri** [comment]
Ok, so I found the root cause for the strange behaviour.
Historically I had installed the deb package before starting development. My deploy script would deploy the new code but leave everything else as-is. Since meanwhile an updated package was available a run of apt-get upgrade tried to overwrite my code, so I uninstalled the package. This also reset the MPD configuration. I recreated that config and the playlists are in sync again.

**Comment by HiranChaudhuri** [comment]
Having fixed the misconfiguration in my system I cannto make the exceptions appear again. Apart from the screen layout all seems fine. I will merge now.

**Comment by Acer54** [comment]
changing lib/players.py from self.client.load("favorites") to ... self.load_playlist("favorites") causes, that you cannot play a radio-station untit you select it as a "favorite" (give him a star..) 
This need to be reverted.

**Comment by HiranChaudhuri** [comment]
> changing lib/players.py from self.client.load("favorites") to ... self.load_playlist("favorites") causes, that you cannot play a radio-station untit you select it as a "favorite" (give him a star..)
> This need to be reverted.

I thought the favorites would contain starred radio stations anyway.
When looking at the code, the method https://github.com/HiranChaudhuri/Webradio_v4/blob/master/opt/webradio-py3/lib/players.py#L67 does not do much different than what you need.

You suggest 
* self.client.load(...)
where the method does
* self.cleint.clear()
* self.client.load(...)
* logging
* error handling

So apart from self.client.clear() there should not be any different in handling MPD. Could you elaborate why this command would suddenly require a radio station to be starred?

**Comment by Acer54** [comment]
The difference is, that the "channel" gets added after self.client.clear()". The failure you where facing is due to the fact, that your mpd.conf file was wrong configured ... not pointing to the "favorites.m3u" ...after fixing that, it would have worked in the expected way.

**Comment by HiranChaudhuri** [comment]
By looking up the [API](https://python-mpd2.readthedocs.io/en/latest/topics/commands.html) now I understand the load shall add favorites into the current playlist rather than replacing the current playlist with just the favorites. That is an issue indeed.

I'd like to have the logging and error handing available but not repeat that part of the code. How about adding a flag to load_playlist whether to replace or merge (which results in the clear() call)?

**Pull request merged**
